documents:
  dynamic_folder: 动态文档
  log_folder: 日志
  static_folder: 静态文档
git:
  branch: main
  remote: ''
llm:
  api_key: sk-6170987690b3a7c3062ccf03587ea6ffa5f82080dcfd5ff613ee0fdc5efee9f4
  model: deepseek-v3
  provider: qiniu
project:
  name: 新项目
  path: ./project_folder
